environment: prod

image:
  name: ifrc/alert-hub-web-app
  tag: latest
  imagePullPolicy: Always

ingress:
  host: alert-hub-1.ifrc-go.org

env:
  APP_TITLE: "Alert hub"
  APP_ENVIRONMENT: ALPHA-1
  APP_MAPBOX_ACCESS_TOKEN: pk.ab.xy
  APP_GRAPHQL_API_ENDPOINT: https://alert-hub-1.ifrc-go.org/graphql/
