version: '3.8'
services:
  react:
    build: .
    command: sh -c 'yarn install && yarn start --host'
    volumes:
      - .:/code
    ports:
      - '3000:3000'
        environment:
 APP_GRAPHQL_ENDPOINT: ${APP_GRAPHQL_ENDPOINT:-http://localhost:8000/graphql/}