services:
  react:
    container_name: alert-hub-web-app
    build:
      context: ../
      target: dev
    command: sh -c "pnpm install && pnpm start"
    volumes:
      - ../:/code
    environment:
      APP_ENVIRONMENT: ${APP_ENVIRONMENT:-DEV}
      APP_TITLE: ${APP_TITLE:-ALERTHUB}
      APP_GRAPHQL_API_ENDPOINT: ${APP_GRAPHQL_API_ENDPOINT:-http://web:8000/graphiql/}
      APP_GRAPHQL_CODEGEN_ENDPOINT: ${APP_GRAPHQL_CODEGEN_ENDPOINT:-./backend/schema.graphql}
    env_file:
      - ../.env
    ports:
      - '3000:3000'
