# NOTE: `../` refers to the web-app folder, relative to `./backend/docker-compose.yml` (the main Docker Compose file).

services:
  # TODO: Define frontend application here
  # react:
  #   command: sh -c 'pnpm install && pnpm start'
  #   build:
  #     context: ../
  #     target: dev
  #   environment:
  #     ... Define required environments here
  #   env_file:
  #     - ../.env
  #   volumes:
  #     - ../:/code
  #   ports:
  #     - '3000:3000'

  web:
    environment:
      APP_ENVIRONMENT: ${APP_ENVIRONMENT:-DEV}
      APP_FRONTEND_HOST: ${APP_FRONTEND_HOST:-http://localhost:3000}
