name: Lint & Build

on:
  pull_request:
  push:
    branches:
      - 'develop'

env:
  APP_ENVIRONMENT: testing
  APP_TITLE: "Alerthub"
  APP_MAPBOX_ACCESS_TOKEN: XYZ
  APP_GRAPHQL_CODEGEN_ENDPOINT: ./backend/schema.graphql
  APP_GRAPHQL_API_ENDPOINT: http://api.example.com/graphql/
  GITHUB_WORKFLOW: true

jobs:
  # unimported:
  #   name: Find unimported files
  #   runs-on: ubuntu-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #       with:
  #         submodules: true
  #    - name: Install pnpm
  #      uses: pnpm/action-setup@v4
  #    - name: Install Node.js
  #      uses: actions/setup-node@v4
  #      with:
  #        node-version: 22
  #        cache: 'pnpm'
  #    - name: Install dependencies
  #      run: pnpm install
  #
  #     - name: Run unimported
  #       run: pnpm unimported
  # fix use better tool, this is deprecated

  lint-js:
    name: Lint JS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Lint Javascript
        run: pnpm generate && pnpm lint:js

  css-lint:
    name: Lint CSS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Css Lint
        run: pnpm lint:css

  typecheck:
    name: Typecheck
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Typecheck
        run: pnpm generate && pnpm typecheck

  build:
    name: Build
    needs: [lint-js, css-lint, typecheck]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          submodules: true
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22
          cache: 'pnpm'
      - name: Install dependencies
        run: pnpm install
      - name: Build
        run: pnpm generate && pnpm build
